### ISSUE TITLE
Removing `build` command and script

### ISSUE THREAD

**Issue by m-bra** [upm-developers/upm#4]
The `build` script has no direct use - it's just prepares for another command, e.g. running, installing/extracting or testing. The package can figure out when it has to build - so the build command is completely unnecessary and should thereby be removed (since it also adds unnecessary complexity)

**Comment by NoahPeeters** [comment]
Thats ok.

**Comment by m-bra** [comment]
Please close if implemented otherwise we're gonna forget it (at least im gonna :laughing: )
