### ISSUE TITLE
Terminology: extract instead of install

### ISSUE THREAD

**Issue by m-bra** [upm-developers/upm#5]
We don't know what's in the package, will usually be a code project, but can also be documentation or something else. Thus I'd talk about extracting stuff out of the package instead of installing. However, the command `install` still persists, and will do the same as `extract`, just for cases where it looks nicer to `install` something.

**Comment by NoahPeeters** [comment]
Do you want to replace `install` or add `extract`? And `extract` can be confusing because it sounds like extracting the downloaded .zip file. And what should the install script of a documentation do. Move it into a global documentation folder?

**Comment by m-bra** [comment]
I just want to make a synonym. Another wording could be `pull`ing. Oh, and the extract/pull/install script of a documentation will: either copy it to the wanted directory, or move to a global documentation folder, like you said. (Sidenote: documenation can also be compiled, like markdown should be converted into html, so its a bit more involved than just copying. And there may be other cases which are not code projects but follow a similar order of building as code projects)

**Comment by m-bra** [comment]
Also, the user does not know of any .zip file being downloaded. (neither did I know that were downloading zips)

**Comment by m-bra** [comment]
Made [proposal](https://github.com/upm-developers/upm-proposals/pull/1)

**Comment by m-bra** [comment]
Confirmed.
