### ISSUE TITLE
Temporary path for package

### ISSUE THREAD

**Issue by m-bra** [upm-developers/upm#6]
Have a command like `upm get-tmp <package>` that always outputs the same temporary path for a package. This is useful if a package wants to save some intermediate files, for example precompiled source files (object files), and _reuse_ them later.
For example, in a bash build script:

```
PKG_DIR=.
TMP_DIR=`upm get-tmp mypack`
cd TMP_DIR
gcc source.c 
gcc -o reused.o source_that_never_changes_and_is_really_big_.c # compiled object file gets saved into temporary
cd PKG_DIR
gcc -ohelloworld $TMP_DIR/source.o $TMP_DIR/reused.o # use object files from temporary
```

Now, the next time the build script gets called the same temporary directy is returned by upm, thus the build script can reuse the really big object file because the source did not change anyways, which will save a lotta time!
Advantages:
- reusing already compiled code -> faster building
- upm can easily and _safely_ delete all temporary directories it allocated (e.g. with `upm clean-all`, jap, that's exactly what you wanted, @NoahPeeters :smile: )
- the normal source package does not change, which is generally good (can build read-only packages, build can not break source package)

If there is a better way or something bad with this idea, let me know

**Comment by NoahPeeters** [comment]
I don't understand that. Isn't that tmp folder the same as the build dir in the package (or do the same)?

**Comment by m-bra** [comment]
Not exactly, it's just a directory that co-exists with a package, _outside_ from that package. 
It serves the same purpose, though.
The packager can still `mkdir` a build folder and do all the stuff there, but because 1) the folder is outside of the package and 2) upm knows its temp, upm can delete it. The packager just asks upm: "Yeah, can I get a folder for some intermediate files (zwischendateien), you can delete it, i don't care, but i want to reuse (wieder benutzen) them the next build is performed!"

**Comment by m-bra** [comment]
The problem for the packager is just: _where_ can i have an outside temp dir?

**Comment by NoahPeeters** [comment]
But why should he want's a tmp dir outside the package and how can he reuse it if upm deletes it.

**Comment by m-bra** [comment]
Well, upm does only delete it when the user wants to clear all temp files (to clear space on the drive).
The idea is: you have one clean package, which does not get touched once sent outside, and for building use a temp folder, where the user can say: okay, clean all that stuff. which will delete temp folders.

**Comment by m-bra** [comment]
Made [proposal](https://github.com/upm-developers/upm-proposals/pull/1)
