### ISSUE TITLE
upm server wiki

### ISSUE THREAD

**Issue by m-bra** [upm-developers/upm#7]
Could please explain [the wiki page](https://github.com/m-bra/upm/wiki/UPM-Servers) in some more detail? What does the save string do, where is it stored, for what? Also, could you include dat system we've been discussing about in the end? Thanks :+1:

**Comment by m-bra** [comment]
e.g. the system between the intermediate servers (Vermittlungsserver) and the actual servers that store the packages.

**Comment by m-bra** [comment]
In the save string: `<name>|{<version1>|<version2>|…}|<hashPass>` why are there versions? I understand the connection between the package name and the `hashPass`, but what do the versions do there? Also with `versions: <version-number>{url1|url2|…}` what is actually done there? (I know it may be a bit hard to create documentation :smile: )

**Comment by NoahPeeters** [comment]
I completely leaved out the http serves witch store the packages. 

The versions in the save string (i need a better name) witch represents a package with all the versions are for saving the urls. The `<versionX>` will be replaced with `<version-number>{url1|url2|…}'`.

**Comment by m-bra** [comment]
Okay, so `versions: <version-number>{url1|url2|…}`  still belongs to a package (is not standalone). Isn't it possible to merge those two expressions to:
`<name> | <version1> : {<url1>, <url2>, ...}, <version2> : ..., ... | <hashPass>`
(actual syntax is not important here as well as spaces)
To read: "name" has "version1" which can be get in "url1" and "url2" (...), and all of this is secured with "hashPass". Am I right?

**Comment by m-bra** [comment]
Oh, and can't the urls be just full identifiers? E.g. instead of sayin `google.com/yes-this-directory-totally-exists/package.zip` just use `google.com:package`, **or** even just `package` which means that the package is installed inside the intermediate server. Why did we actually not take that into account? That the intermediate server can store the packages _directly_.

**Comment by NoahPeeters** [comment]
First answer
Yes your right but we can't split the urls with `,` because thats an allowed character in urls. Thats why I used the `|`.

Second answer
I would not use `google.com:package` because the http server may run on another port or the packages are saved in a sub dir (Maybe on the normal port 80 is a web interface). And the package can be on the same intermediate server if there is a http server too.

**Comment by m-bra** [comment]
Oh ya forget my proposal about url replace to identifier.
However, I don't like the way the urls are specified to the versions of the package. I would have two lists:
Passwords and package locations.
Passwords are easy: every package name (not identifier, just the name) is locked with a password (what you already did there). So we have a list like i dunno 

```
<name>|<pass>
clang|123456
```

This file "locks" the names.

Then there is a "resolver" which takes an identifier and returns a location to download from (which does not have to be another server, right?)
like

```
clang:4.8_debug|google.com/clang_4_8_debug.zip
clang:4.9_|google.com/clang_4_9_.zip
```

And whenever someone asks to change/add a package, upm first looks into lock and will ask for a password and compare (or add), and then look into the "resolver" file.
And if someone asks to just download, omit looking into lock file.
This way the problem of "locking" package names and "resolving" package identifiers are seperated (and seperating problems is always good)
This way the resolving of an identifier.

> And the package can be on the same intermediate server if there is a http server too.
> What do you mean by " if there is a http server too."? the intermediate server can just store the package on its own, without external servers

**Comment by m-bra** [comment]
Oh, and how does upm know _which_ url to use for downloading

**Comment by NoahPeeters** [comment]
Two things: 
1. How does the server/client finds all the versions. He only knows the name and in your version it's much more complicated to find all available versions of a package.
2. My idea was that upm tries to download the package from the first url and if the server does not work it tries the second and so on.

**Comment by m-bra** [comment]
1. "He only knows the name" who and from where? I have an example: upm user sends to server: please get me the package, the identifier is `clang`. The user could also say that the identifier is `clang>2.8`. Now we simply go through all the registered package identifiers, and have a list of all matching packages. (-> that is the `search` command). Then we take the package with the highest version, get that url. I don't think that this is complicated, we are even reusing the `search` command.
2. That's good. I'll update my proposal:  

> Then there is a "resolver" which takes an identifier and returns a location to download from (which does not > have to be another server, right?)
> like

```
 clang:4.8_debug|google.com/clang_4_8_debug.zip, web.de/clang_4_8_debug.tar.gz 
 clang:4.9_|google.com/clang_4_9_.zip, web.de/clang_4_9_.tar.gz
```

**Comment by m-bra** [comment]
2. Ok, that's good.

**Comment by m-bra** [comment]
Updated comment, reload page.

**Comment by m-bra** [comment]
Also, in my version the package identifier stays in its form, and the normal parsing can be used, thus reusing code, thus less coding, thus less bugs, thus better code, in yours it is splitted thus needs to parsed in a special way.

**Comment by m-bra** [comment]
> The save string is used to save the information about a package in a file (for example after a crash and/or a server restart)  

Why after crash/restart? I think it needs it for downloading a package or changing settings of a package?

**Comment by NoahPeeters** [comment]
I thought, that we have the information of the packages in an array, so that we can acces them quick. So the file would only be a backup. I don't know how much extra time we need, if we read the information directly from the file. Would it be possible that multiple programs read and one program writes to the file? Or does they block/slow down each other.

**Comment by m-bra** [comment]
Oh, you mean, the package information is stored in the RAM of the server rather than in a file to speed reading and writing up. Well, I'd say, that "officially", the package info is stored in a file, it's safe there. We can put it in the RAM "under the hood". This kinda problem is not important now, however. This is implementation detail.

**Comment by m-bra** [comment]
It's possible that multiple processes share a resource, this will result in a [race condition](http://stackoverflow.com/questions/34510/what-is-a-race-condition).

**Comment by NoahPeeters** [comment]
This issue was moved to upm-developers/upm-server#3
