### ISSUE TITLE
Server security issue

### ISSUE THREAD

**Issue by NoahPeeters** [upm-developers/upm#9]
If multiple serves stay in sync and someone makes a change on one server, the server has to send the new information to all the other servers. But where does these servers know from that the server who wants to make changes is a trusted server.

My idea was that all these servers not only have a list of host but also a list of IDs that are allowed (similar to the password the packager sets to his package). That would cause, that to servers only stay in sync, if they have the domain and the ID/password of the other one.

**Comment by m-bra** [comment]
Sounds okay, but please explain in more detail

**Comment by NoahPeeters** [comment]
This issue was moved to upm-developers/upm-server#1
